# Generated by Django 6.0.5 on 2026-07-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0004_remove_narsalar_name_narsalar_narxi_narsalar_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_limit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzmovi.agelimit')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzmovi.country')),
                ('genres', models.ManyToManyField(related_name='movies', to='uzmovi.genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzmovi.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Narsalar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
