# Generated by Django 6.0.5 on 2026-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0004_remove_narsalar_name_narsalar_narxi_narsalar_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('janr', models.CharField(max_length=100)),
                ('yili', models.PositiveIntegerField()),
                ('tili', models.CharField(max_length=50)),
                ('davomiyligi', models.CharField(max_length=50)),
                ('yosh_chegarasi', models.CharField(max_length=20)),
                ('treyler', models.URLField(blank=True, null=True)),
                ('asosiy', models.BooleanField(default=False)),
                ('izoh', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Narsalar',
        ),
    ]
