# Generated by Django 6.0.5 on 2026-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0005_kino_delete_category_delete_narsalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='banner/')),
                ('yozuv', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Kino',
        ),
    ]
