# Generated by Django 6.0.5 on 2026-07-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0005_agelimit_country_genre_language_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Davlat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Davomiylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.CharField(max_length=50, verbose_name='Davomiyligi')),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Janr nomi')),
            ],
        ),
        migrations.CreateModel(
            name='KinoNomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Kino nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='Tili')),
            ],
        ),
        migrations.CreateModel(
            name='Yil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(max_length=10, verbose_name='Yili')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.davlat', verbose_name='Davlati')),
                ('davomiylik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.davomiylik', verbose_name='Davomiyligi')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.janr', verbose_name='Janri')),
                ('kino_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.kinonomi', verbose_name='Kino nomi')),
                ('til', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.til', verbose_name='Tili')),
                ('yil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.yil', verbose_name='Yili')),
            ],
        ),
        migrations.DeleteModel(
            name='AgeLimit',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
