# Generated by Django 6.0.5 on 2026-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0006_davlat_davomiylik_janr_kinonomi_til_yil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kino',
            name='davlat',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='davomiylik',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='janr',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='kino_nomi',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='til',
        ),
        migrations.RemoveField(
            model_name='kino',
            name='yil',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Davlat',
        ),
        migrations.DeleteModel(
            name='Davomiylik',
        ),
        migrations.DeleteModel(
            name='Janr',
        ),
        migrations.DeleteModel(
            name='KinoNomi',
        ),
        migrations.DeleteModel(
            name='Til',
        ),
        migrations.DeleteModel(
            name='Kino',
        ),
        migrations.DeleteModel(
            name='Yil',
        ),
    ]
