# Generated by Django 6.0.5 on 2026-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0006_banner_delete_kino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='sarlavha',
        ),
        migrations.AlterField(
            model_name='banner',
            name='yozuv',
            field=models.CharField(max_length=255),
        ),
    ]
