# Generated by Django 6.0.5 on 2026-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0007_remove_kino_davlat_remove_kino_davomiylik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='qoshimcha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
