# Generated by Django 6.0.5 on 2026-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0007_remove_banner_sarlavha_alter_banner_yozuv'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('janr', models.CharField(max_length=255)),
                ('davlati', models.CharField(max_length=255)),
                ('yili', models.IntegerField()),
                ('tili', models.IntegerField()),
                ('davomiyligi', models.IntegerField()),
                ('yosh', models.IntegerField()),
                ('izoh', models.TextField()),
            ],
        ),
    ]
