# Generated by Django 6.0.5 on 2026-07-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0008_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavlatCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JanrCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('tili', models.CharField(max_length=255)),
                ('davomiyligi', models.CharField(max_length=100)),
                ('yosh', models.CharField(max_length=100)),
                ('izoh', models.TextField()),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.davlatcategory')),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.janrcategory')),
            ],
        ),
        migrations.CreateModel(
            name='YilCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yil', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AddField(
            model_name='kino',
            name='yil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzmovi.yilcategory'),
        ),
    ]
